# Generated by Django 4.2.5 on 2023-10-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OlxCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclename', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=300)),
                ('number', models.CharField(max_length=15)),
                ('price', models.PositiveIntegerField()),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
